apply plugin: 'com.android.library'
apply plugin: 'com.github.dcendents.android-maven'
group='com.github.freshdesk'

def static getEscapedString(value) {
    return "\"$value\"";
}

def getScmRevision = {
    String rev = 'git rev-parse --short HEAD'.execute().text.trim()
    return getEscapedString(rev)
}

def getScmBranch = {
    String branch = "git rev-parse --abbrev-ref HEAD".execute().text.trim()
    return getEscapedString(branch)
}

android {
    compileSdkVersion 36
    buildToolsVersion "29.0.3"

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    buildFeatures {
        buildConfig = true
    }

    defaultConfig {
        minSdkVersion 23
        versionCode 6512
        versionName "6.5.12"
        targetSdkVersion 36
        consumerProguardFiles 'consumer-proguard-rules.pro'
        buildConfigField "long", 'BUILT_AT', System.currentTimeMillis() + 'L'
        buildConfigField "String", "SCM_REV", getScmRevision()
        buildConfigField "String", "SCM_BRANCH", getScmBranch()
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'sdk-proguard-rules.pro'
        }
    }
}

ext {
    gsonVersion             = '2.11.0'
    picassoVersion          = '2.8'
    circleImageViewVersion  = '3.1.0'
    appcompatVersion        = '1.7.1'
    recyclerviewVersion     = '1.4.0'
    materialVersion         = '1.13.0'
    cardviewVersion         = '1.0.0'
    localbroadcastmanagerVersion = '1.1.0'
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation "com.google.code.gson:gson:$gsonVersion"
    implementation "com.squareup.picasso:picasso:$picassoVersion"
    implementation "androidx.appcompat:appcompat:$appcompatVersion"
    implementation "androidx.recyclerview:recyclerview:$recyclerviewVersion"
    implementation "com.google.android.material:material:$materialVersion"
    implementation "androidx.cardview:cardview:$cardviewVersion"
    implementation "androidx.localbroadcastmanager:localbroadcastmanager:$localbroadcastmanagerVersion"
    implementation "de.hdodenhof:circleimageview:$circleImageViewVersion"
}
